name: CI Failure Log Handler

on:
  workflow_run:
    workflows: ["CI Workflow"]  # Replace with your actual workflow name
    types:
      - completed

jobs:
  handle-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download logs
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            const run_id = process.env.GITHUB_RUN_ID;
            const token = process.env.GITHUB_TOKEN;

            const logsUrl = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/actions/runs/${run_id}/logs`;
            execSync(`curl -H "Authorization: token ${token}" -L ${logsUrl} -o logs.zip`);

      - name: Unzip logs
        run: unzip logs.zip -d logs

      - name: Upload logs to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'logs'
