name: CI Failure Log Handler

on:
  workflow_run:
    workflows: ["CI Workflow"]  # Replace with your actual workflow name
    types:
      - completed

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 273354635930
  AWS_S3_BUCKET: <provide-s3-bucket>

jobs:
  handle-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download logs from CI Workflow run
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/logs \
            -o logs.zip

      - name: Verify logs.zip is valid
        run: file logs.zip

      - name: Unzip logs
        run: unzip logs.zip -d logs

      - name: Upload logs to S3
        run: aws s3 sync logs s3://${{ env.AWS_S3_BUCKET }}/ci-failure-logs/${{ github.event.workflow_run.id }} --acl private --follow-symlinks
